
const CoreId={ENTITY:'entity',DATA_TYPE:'datatype',BOOLEAN:'bool',INT:'int',FLOAT:'float',STRING:'string',MAX_VALUE:'max_value',MIN_VALUE:'min_value',MAX_LENGTH:'max_length',MIN_LENGTH:'min_length',SINGLE_LINE:'single_line',MULTIPLE_VALUE:'multiple_value',EXPAND_VALUE:'expand_value',C_COMMANDED:'c_commanded',REGEXP:'regexp',UNIQUE:'unique',ACTIVE_PROPERTY:'active_property'};try{module.exports=CoreId;}catch(e){}
var Property_ActiveProperty={_activeProperties:[],activeProperties:function(){return this._activeProperties},checkValueAsProperty:function(entity,value){if(this._activeProperties.indexOf(entity.id)===-1){this._activeProperties.push(entity.id);}
return value;}};function Entity(){}
Entity.prototype.is=function(parentEntityId){var parent=parentEntityId;if(typeof parent==='string'||parent instanceof String){parent=Entity._entities[parentEntityId];}
var me=this;while(true){if(me.parentId===parent.id||me.id===parent.id)return true;if(me.parentId===null)return false;me=Entity._entities[me.parentId];}};Entity.prototype.isFor=function(childEntityId){var child=childEntityId;if(typeof child==='string'||child instanceof String){child=Entity._entities[childEntityId];}
var me=this;while(true){if(me.id===child.parentId)return true;if(child.parentId===null)return false;child=Entity._entities[child.parentId];}};Entity.prototype.setValue=function(property,value){var propertyId=Entity._getPropertyId(property);property=Entity.get(propertyId);if(property.isMultiple()){this.addValue(property,value);}else{value=Entity._checkValue(this,propertyId,value);this[propertyId]=value;}};Entity.prototype.addValue=function(property,value){var propertyId=Entity._getPropertyId(property);value=Entity._checkValue(this,propertyId,value);property=Entity.get(propertyId);if(!property.isMultiple()){throw new EntityError(EntityErrorId.NotMultiple,'Property "'+propertyId+'" must has "multiple_value=true" to store several values!');}
if(this[propertyId]===undefined){this[propertyId]=[value];}else if(this.hasOwnProperty(propertyId)){this[propertyId].push(value);}else{if(property.hasProperty(CoreId.EXPAND_VALUE)&&property[CoreId.EXPAND_VALUE]){this[propertyId]=this[propertyId].slice();this[propertyId].push(value);}else{this[propertyId]=[value];}}};Entity.prototype.getValue=function(property){property=Entity._getPropertyId(property);this._checkPropertyId(property);return this[property];};Entity.prototype.hasProperty=function(property){property=Entity._getPropertyId(property);return this[property]!==undefined;};Entity.prototype.isMultiple=function(){return this.hasProperty(CoreId.MULTIPLE_VALUE)&&this[CoreId.MULTIPLE_VALUE];};Entity.prototype.contains=function(property,value){property=Entity._getPropertyId(property);this._checkPropertyId(property);if(Array.isArray(this[property])||this[property]instanceof Array){var toRemoveIndex=this[property].indexOf(value);if(toRemoveIndex>-1){return true;}}else if(this[property]===value){return true;}
return false;};Entity.prototype.removeProperty=function(property){property=Entity._getPropertyId(property);if(this[property]===undefined||!this.hasOwnProperty(property))return;delete this[property];};Entity.prototype.removeValue=function(property,value){property=Entity._getPropertyId(property);if(this[property]===undefined||!this.hasOwnProperty(property))return;if(Array.isArray(this[property])||this[property]instanceof Array){var toRemoveIndex=this[property].indexOf(value);if(toRemoveIndex>-1){this[property].splice(toRemoveIndex,1);if(this[property].length===1){this[property]=this[property][0];}}}else if(this[property]===value){this.removeProperty(property);}};Entity.prototype._checkPropertyId=function(propertyID){if(this[propertyID]===undefined){throw new EntityError(EntityErrorId.UndefinedProperty,'Undefined property "'+propertyID+'"');}};Entity._entities={};Entity._implementations={};Entity.clear=function(){Entity._entities={};Entity._implementations={};Entity._initValues();};Entity.contains=function(entityId){return Entity._entities[entityId]!==undefined;};Entity._initValues=function(){Entity.defineImplementationForEntity(CoreId.INT,DataType_Int);Entity.defineImplementationForEntity(CoreId.FLOAT,DataType_Float);Entity.defineImplementationForEntity(CoreId.STRING,DataType_String);Entity.defineImplementationForEntity(CoreId.SINGLE_LINE,Property_SingleLine);Entity.defineImplementationForEntity(CoreId.REGEXP,Property_Regexp);Entity.defineImplementationForEntity(CoreId.UNIQUE,Property_Unique);Entity.defineImplementationForEntity(CoreId.ACTIVE_PROPERTY,Property_ActiveProperty);var entity=Entity.create(CoreId.ENTITY,null);var dataType=Entity.create(CoreId.DATA_TYPE,entity);Entity.create(CoreId.BOOLEAN,dataType);Entity.create(CoreId.INT,dataType);Entity.create(CoreId.FLOAT,dataType);Entity.create(CoreId.STRING,dataType);Entity.create(CoreId.ACTIVE_PROPERTY,CoreId.BOOLEAN);Entity.create(CoreId.MAX_VALUE,CoreId.INT);Entity.create(CoreId.MIN_VALUE,CoreId.INT);Entity.create(CoreId.MAX_LENGTH,CoreId.INT);Entity.create(CoreId.MIN_LENGTH,CoreId.INT);Entity.create(CoreId.SINGLE_LINE,CoreId.BOOLEAN);Entity.create(CoreId.MULTIPLE_VALUE,CoreId.BOOLEAN);Entity.create(CoreId.EXPAND_VALUE,CoreId.BOOLEAN);var regexp=Entity.create(CoreId.REGEXP,CoreId.STRING);regexp.setValue(CoreId.SINGLE_LINE,true);Entity.create(CoreId.C_COMMANDED,CoreId.BOOLEAN);var unique=Entity.create(CoreId.UNIQUE,CoreId.BOOLEAN);unique.setValue(CoreId.ACTIVE_PROPERTY,true);};Entity.get=function(entityId){entityId=Entity._getPropertyId(entityId);if(Entity._entities[entityId]===undefined){throw new EntityError(EntityErrorId.UnknownEntity,'Unknown entity "'+entityId+'"');}
return Entity._entities[entityId];};Entity.create=function(newEntityId,parentEntityId){newEntityId=Entity._getPropertyId(newEntityId);if(parentEntityId===undefined)parentEntityId=null;parentEntityId=Entity._getPropertyId(parentEntityId);if(parentEntityId!==null&&Entity._entities[parentEntityId]===undefined){Entity.create(parentEntityId);}
if(Entity._entities[newEntityId]===undefined){var entity;if(parentEntityId===null){entity=new Entity(newEntityId,parentEntityId);}else{entity=Object.create(Entity._entities[parentEntityId]);var implementation=Entity._findImplementation(newEntityId);for(var prop in implementation){entity[prop]=implementation[prop];}}
entity.id=newEntityId;entity.parentId=parentEntityId;Entity._entities[newEntityId]=entity;}else{Entity._entities[newEntityId].parentId=parentEntityId;}
return Entity._entities[newEntityId];};Entity.defineImplementationForEntity=function(entityId,implementation){Entity._implementations[entityId]=implementation;};Entity._findImplementation=function(entityId){if(Entity._implementations[entityId]!==undefined){return Entity._implementations[entityId];}
return{};};Entity._checkValue=function(entity,propertyId,value){if(value===null)return null;var property=Entity.get(propertyId);if(property.is(CoreId.BOOLEAN)){if(!(typeof value==='boolean'||value instanceof Boolean))
throw new EntityError(EntityErrorId.NotBoolean,'Value for "'+propertyId+'" must be boolean but was '+value);}else if(property.is(CoreId.INT)){if(!(typeof value==='number'||value instanceof Number)){throw new EntityError(EntityErrorId.NotInt,'Value for "'+propertyId+'" must be int but was '+value);}
if(value%1!==0){throw new EntityError(EntityErrorId.NotInt,'Value for "'+propertyId+'" must be int but was '+value);}}else if(property.is(CoreId.FLOAT)){if(!(typeof value==='number'||value instanceof Number)){throw new EntityError(EntityErrorId.NotFloat,'Value for "'+propertyId+'" must be number but was '+value);}}else if(property.is(CoreId.STRING)){if(!(typeof value==='string'||value instanceof String)){if(value.is!==null&&typeof value.is==='function'&&value.is(CoreId.ENTITY)){value=value.id;}else{throw new EntityError(EntityErrorId.NotString,'Value for "'+propertyId+'" must be string but was '+value);}}}else{var valueEntity=Entity.get(value);if(!valueEntity.is(property)){if(!property.hasProperty(CoreId.C_COMMANDED)||!property[CoreId.C_COMMANDED]||!valueEntity.is(property.parentId)){throw new EntityError(EntityErrorId.NotParticularEntity,'Value for "'+propertyId+'" must be "'+property.id+'" but was '+valueEntity.id);}}}
if(property.checkValueAsProperty!==undefined){value=property.checkValueAsProperty(entity,value);}
var active=Entity.get(CoreId.ACTIVE_PROPERTY);if(active!==undefined){var activeProperties=active.activeProperties();for(var i=0;i<activeProperties.length;i++){if(property.hasProperty(activeProperties[i])&&property[activeProperties[i]]){value=Entity.get(activeProperties[i]).checkValueAsActiveProperty(property,entity,value);}}}
if(entity.checkValueAsEntity!==undefined){value=entity.checkValueAsEntity(property,value);}
return value;};Entity._getPropertyId=function(property){if(property===null)return property;if(typeof property==='string'||property instanceof String){return property;}else if(typeof property==='object'||property instanceof Object){return property.id;}
return property;};Entity.remove=function(entity){var entityId=Entity._getPropertyId(entity);delete Entity._entities[entityId];};Entity._initValues();function EntityLoader(){}
EntityLoader.proceedJsonDocument=function(dataJson){var data=JSON.parse(dataJson);EntityLoader.proceedDocumentObject(data);};EntityLoader.proceedDocumentObject=function(dataObject){for(var entityId in dataObject){var entityOb=dataObject[entityId];var parentEntityId=entityOb.is===undefined?'entity':entityOb.is;if(parentEntityId==null)parentEntityId=undefined;var entity=Entity.contains(entityId)?Entity.get(entityId):Entity.create(entityId,parentEntityId);}
for(var entityId in dataObject){var entityOb=dataObject[entityId];var entity=Entity.get(entityId);EntityLoader._proceedProperties(entity,entityOb);}};EntityLoader._proceedValue=function(entity,propertyId,value,isMultiple){if((typeof value==='boolean'||value instanceof Boolean)||(typeof value==='number'||value instanceof Number)||value===null){isMultiple?entity.addValue(propertyId,value):entity.setValue(propertyId,value);return;}
if(typeof value==='string'||value instanceof String){if(Entity.contains(value)){value=Entity.get(value);}
isMultiple?entity.addValue(propertyId,value):entity.setValue(propertyId,value);return;}
if(Array.isArray(value)){entity.removeProperty(propertyId);for(var i=0;i<value.length;i++){EntityLoader._proceedValue(entity,propertyId,value[i],true);}
return;}
if(typeof value==='object'||value instanceof Object&&value.id!==undefined){var subEntityObj=value;var subEntity=Entity.contains(subEntityObj.id)?Entity.get(subEntityObj.id):Entity.create(subEntityObj.id,propertyId);EntityLoader._proceedProperties(subEntity,subEntityObj);isMultiple?entity.addValue(propertyId,subEntity):entity.setValue(propertyId,subEntity);}};EntityLoader._proceedProperties=function(entity,entityObject){for(var propertyId in entityObject){if(propertyId==='is')continue;if(propertyId==='id')continue;var value=entityObject[propertyId];EntityLoader._proceedValue(entity,propertyId,value,false);}};function EntityError(id,message){this.id=id;this.message=message;}
var EntityErrorId={UnknownEntity:1,UndefinedProperty:2,NotBoolean:10,NotInt:11,NotFloat:12,NotString:13,NotParticularEntity:14,NotMultiple:50,ConditionMaxValue:100,ConditionMinValue:101,ConditionRegexp:110,ConditionMaxLength:111,ConditionMinLength:112,ConditionSingleLine:113,RegexpForStringsOnly:200,SingleLineForStringsOnly:201,MaxLengthForStringsOnly:202,MinLengthForStringsOnly:203,NotUniqueValue:1000};var DataType_Float={checkValueAsProperty:function(entity,value){if(this[CoreId.MAX_VALUE]!==undefined&&value>this[CoreId.MAX_VALUE]){throw new EntityError(EntityErrorId.ConditionMaxValue,'Value for "'+this.id+'" must be <= '+this[CoreId.MAX_VALUE]+' but was '+value);}
if(this[CoreId.MIN_VALUE]!==undefined&&value<this[CoreId.MIN_VALUE]){throw new EntityError(EntityErrorId.ConditionMinValue,'Value for "'+this.id+'" must be <= '+this[CoreId.MAX_VALUE]+' but was '+value);}
return value;}};var DataType_Int={checkValueAsProperty:function(entity,value){if(this[CoreId.MAX_VALUE]!==undefined&&value>this[CoreId.MAX_VALUE]){throw new EntityError(EntityErrorId.ConditionMaxValue,'Value for "'+this.id+'" must be <= '+this[CoreId.MAX_VALUE]+' but was '+value);}
if(this[CoreId.MIN_VALUE]!==undefined&&value<this[CoreId.MIN_VALUE]){throw new EntityError(EntityErrorId.ConditionMinValue,'Value for "'+this.id+'" must be <= '+this[CoreId.MAX_VALUE]+' but was '+value);}
return value;}};var Property_Regexp={checkValueAsProperty:function(entity,value){if(!entity.is(CoreId.STRING)){throw new EntityError(EntityErrorId.RegexpForStringsOnly,'Regexp can be applied to string properties only, but property is "'+this.id+'"');}
return value;}};var Property_SingleLine={checkValueAsProperty:function(entity,value){if(!entity.is(CoreId.STRING)){throw new EntityError(EntityErrorId.SingleLineForStringsOnly,'"single_line" can be applied to string properties only, but property is "'+this.id+'"');}
return value;}};var DataType_String={checkValueAsProperty:function(entity,value){if(this[CoreId.MAX_LENGTH]!==undefined&&value.length>this[CoreId.MAX_LENGTH]){throw new EntityError(EntityErrorId.ConditionMaxLength,'Length of string value for "'+this.id+'" must be <= '+this[CoreId.MAX_VALUE]+' but was '+value.length);}
if(this[CoreId.MIN_LENGTH]!==undefined&&value.length<this[CoreId.MIN_LENGTH]){throw new EntityError(EntityErrorId.ConditionMinLength,'Length of string value for "'+this.id+'" must be <= '+this[CoreId.MAX_VALUE]+' but was '+value.length);}
if(this[CoreId.SINGLE_LINE]!==undefined&&this[CoreId.SINGLE_LINE]&&value.indexOf('\n')!=-1){throw new EntityError(EntityErrorId.ConditionSingleLine,'String value for "'+this.id+'" must be single line but was "'+value+'"');}
if(this[CoreId.REGEXP]!==undefined&&!value.match(new RegExp(this[CoreId.REGEXP]))){throw new EntityError(EntityErrorId.ConditionRegexp,'String value "'+value+'" for "'+this.id+'" doesn\'t match to regexp "'+this[CoreId.REGEXP]+'"');}
return value;}};var Property_Unique={_values:{},checkValueAsActiveProperty:function(property,entity,value){if(this._values[property.id]===undefined){this._values[property.id]=[];}
if(this._values[property.id].indexOf(value)!==-1){throw new EntityError(EntityErrorId.NotUniqueValue,'Value for property "'+property.id+'" must be unique, but value "'+value+'" was already used');}
this._values[property.id].push(value);}};